# In-Class Programming Activity, Day 6

## Diana Luc

## Task 1
```{r}
library(mosaicData)

myHistogram <- function(v,fill, nbins) {

  evenly_spaced <- seq(min(v), max(v), length.out = nbins + 1)

  bin_counts <- table(cut(v, evenly_spaced))

  hist_basics <- data.frame("xL" = evenly_spaced[1:(nbins)] ,"xR" = evenly_spaced[2:(nbins+1)],"count" = as.numeric(bin_counts))

  My_bars <- data.frame(one_to_five(hist_basics))

plot(My_bars, type = "n", xlab = "Height", ylab = "Count", main = "Height Measurements")
lines(My_bars)
polygon(My_bars, col = fill)

mean <- mean(Galton$height)
SD <- sd(Galton$height)
x <- seq(min(Galton$height), max(Galton$height))
height <- sum(diff(evenly_spaced)*hist_basics$count)

lines(x, height * dnorm(x,mean,SD))


return(bin_counts)
}

make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}

myHistogram(Galton$height, "seashell", 15)
```
## Task 2
```{r}
v <-c(rnorm(10,mean=100, sd = 1))

bw <- diff((range(v)) / sqrt(length(v)))

kernel <- function(x, bw) {
 dnorm(x, mean = 0, sd = bw)
}

x_vals <- seq(min(v)-4*bw, max(v)+4*bw, length = 200)

Dvals <- colSums(outer(v, x_vals, FUN= function(x,y){ kernel (x-y, bw)}/length(v)))

plot(x_vals,Dvals)
```
## Task 3
```{r}
plotdensity <- function(v, xlim=NULL){
  bw <- diff((range(v)) / sqrt(length(v)))

  kernel <- function(x, bw) {
 dnorm(x, mean = 0, sd = bw)
}

x_vals <- seq(min(v)-4*bw, max(v)+4*bw, length = 200)

Dvals <- colSums(outer(v, x_vals, FUN= function(x,y){ kernel (x-y, bw)}/length(v)))

dframe <- data.frame(x_vals,Dvals)
invisible(dframe)
}
```

## Test statements

```{r}
scoreActivity::score253(6)
```