# In-Class Programming Activity, Day 10

## Diana Luc

```{r}
library(ISLR)
data(Default, package = "ISLR")

logistic <- function(x) {
  value <- exp(x) / (1+exp(x))
  return (value)
}
```

```{r}
linear_combine <- function(data, coefs) {
  
  result <- 0
for (nm in names(coefs)) {
  if (nm == "intercept") {
    result <- result + coefs[[nm]]
  } else if (!nm %in% names(data)) {
    stop("doesn't exist")
  } else {
    result <- result + coefs[[nm]] * data[[nm]]
    }
  }
  return(result)
}
```

```{r}
LL_logistic <- function(data, coefs, outcome){
  ans1 <- linear_combine(data,coefs)
  probs <- logistic(ans1)
  likes <- ifelse(outcome == 1, probs, 1-probs) 
  sum(log(likes))
}
```

```{r}
LL_logistic(data=Default, 
            coefs = c(intercept = 1, income = -0.0001), 
            outcome = Default$default == "Yes")
```

```{r}
best_coefs <- optim(c(intercept = 1, income = -0.0001),LL_logistic, control = list(fnscale = -1), data=Default, outcome = Default$default == "Yes")

best_coefs

glm(default == "Yes" ~ income, data=Default, family="binomial")
```

## Test statements

```{r}
scoreActivity::score253(10)
```