# In-Class Programming Activity, Day 14

## Diana Luc
## March 28, 2017

```{r}
library(glmnet)
GenCont <- read.csv("http://tiny.cc/dcf/GenCont.csv")
```

```{r}
compare_ols_ridge <- function(responses, predictors, lambda=1){
  ind <- sample(1:nrow(GenCont), size = nrow(GenCont)/2)
  
  GenTrain <- predictors[ind,]
  GenTest <- predictors[-ind,]
  
  GenLog <- lm(responses[ind] ~ as.matrix(GenTrain))
  GenRidge <- glmnet(as.matrix(GenTrain), responses[ind], alpha = 0)
  
  preds_in <- predict(GenLog, newdata = GenTrain)
  preds_out <- predict(GenLog,newdata = GenTest)
  
  glm_in <- predict.glmnet(GenRidge, newx = GenTrain)
  glm_out <- predict.glmnet(GenRidge, newx = GenTest)
  
  ols_in <- mean((preds_in ~ responses[ind])^2)
  ols_out <- mean((preds_out~responses[ind])^2)
  
  glm_ols_in <- mean((glm_in ~ responses[ind])^2)
  glm_ols_out <- mean((glm_out ~ responses[-ind])^2)
  
  Shrink_results <- list(lambda = lambda, ols_in = ols_in, ols_out = ols_out, glm_in = glm_in, glm_out = glm_out)
  
}

#compare_ols_ridge(GenCont$Phenotypes, GenCont[,-1]) 

#Above command pulls a error that I don't know how to solve. It says predication from a rank-deficient fit may be misleading predication from a rank-deficient fit may be misleading. 
```



## Test statements

```{r}
scoreActivity::score253(14)
```