# In-Class Programming Activity, Day 16

## Diana Luc
## April 6, 2017

## The knots

```{r}
my_knots <- function(x,k){
  qs <-  (1:k)/(1+k)
  #qs <- seq(1/(k+1), .9999, by = 1/(k+1))
  quantile(rnorm(1000), probs=qs)
}

my_knots(rnorm(1000),2)
```

## The basis set

```{r}
spline_model_matrix<- function(x, knot_locations) {
  MM <- cbind(1, x, x^2, x^3)
  for (i in knot_locations) {
    new_vector <- (x-knot_locations[i])^3
    MM <- cbind(MM, new_vector)
  }
  return (MM)
}
```

## Finding the best linear combination

```{r}
#spline_coefs <- coef(lm(y ~ MM))

fit_spline <- function(formula, k=2, data=parent.frame()) {
  y <- eval(formula[[2]], envir=data)
  x <- eval(formula[[3]], envir=data)
  knot_locations <- my_knots(x, k)
  MM <- spline_model_matrix(x, knot_locations)
  mod <- lm(y ~ MM - 1)
  res <- list(coef = coef(mod), knots = knot_locations, cov = vcov(mod))
  class(res) <- "my_spline"
  
  return(res)
}
```

## The predict function

```{r}
predict.my_spline <- 
  function(mod, newx, level = 0.95,
           intervals=c("none", "confidence", "prediction")) {
  intervals <- match.arg(intervals)
  MM <- spline_model_matrix(newx, mod$knots)
  vals <- MM %*% mod$coef
  se <- sqrt(rowSums(MM %*% mod$cov * MM))
  if (intervals == "none") return(vals)
  else return(NULL) # for future use
}
```

## Test statements

```{r}
scoreActivity::score253(16)
```